<?php
$title = 'Edit General Configs';
$this->headTitle($title);
?>
<h1><?= $this->translate($title) ?> </h1>

<?php
$formType = 'horizontal';
$displayOptions = array(
    'elements'              => array(
        'submit'             => array(
            'class'                 => 'btn-large',
        ),
    ),
);

$form = $this->form;
$form->setAttribute('action', $this->url('admin/libra-app/config/general', array('action' => 'edit')));
$form->prepare();

//output messages:
if ($form->getMessages()):
?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        The form fields are not filled out correctly.
    </div>
<?php
endif;

//echo $this->formTwb($form, $formType, $displayOptions);
echo $this->form($form, $formType, $displayOptions);
?>
