<?php
$user = null;

$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$modulePath = $basePath . '/vendor/libra/libra-app';
$layoutPath = $basePath . '/vendor/libra/libra-app/admin-layout/default';
$this->headLink()->appendStylesheet($basePath . '/vendor/twitterbootstrap/css/bootstrap.min.css')
                 //->appendStylesheet($basePath . '/vendor/jquery-ui/css/flick/jquery-ui-1.8.18.custom.css')
                 ->appendStylesheet($basePath . $layoutPath . '/css/style.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $modulePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()
    ->appendFile($basePath . $modulePath . '/js/html5.js', 'text/javascript',
        array('conditional' => 'lt IE 9',))
    //->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js')
    ->appendFile('/vendor/jquery-ui/js/jquery-1.7.1.min.js')
    //->appendFile('/vendor/jquery-ui/js/jquery-ui-1.8.18.custom.min.js')
    ->appendFile('/vendor/twitterbootstrap/js/bootstrap.js')
    ;

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php $this->headTitle('Administration') ?>
    <?php echo $this->headTitle('Libra CMS') ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>

    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
            <a class="brand" href="<?php echo $this->url('admin/home') ?>">♎</a>

          <div class="nav-collapse">
            <?php echo $this->navigation() ?>
            <ul class="nav">
              <li class="divider-vertical"></li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  Configuration
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                      <a href="<?php echo $this->url('default', array('controller' => 'general', 'action' => 'edit')) ?>" onclick="$('generalModal').modal()">
                      <i class="icon-cog"></i> General
                    </a>
                   </li>
                  <li>
                    <a href="<?php echo $this->url('default', array('controller' => 'translation', 'action' => 'index')) ?>">
                      <i class="icon-retweet"></i> Translation
                    </a>
                   </li>
                </ul>
              </li>
            </ul>
            <p class="navbar-text pull-right">
              <a href="/" style="margin-right: 100px;">View Site</a>
              <a href="<?php echo $this->url('zfcuser') ?>"><?php echo $this->translate('Hi').' '/*.$user->getDisplayName()*/ ?></a>
            </p>
          </div><!--/.nav-collapse -->

        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
          <?php echo $this->toolbar ?>
      </div>
      <div class="row-fluid">
          <?php echo $this->content ?>
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; 2008 - <?php echo date('Y') ?> by Ejoom Software Inc. All rights reserved.</p>
      </footer>

    </div><!--/.fluid-container-->
    <?php echo $this->inlineScript() ?>
  </body>

</html>
