<?php
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$modulePath = $basePath . '/vendor/libra/libra-app';
$layoutPath = $basePath . '/vendor/libra/libra-app/layout/admin-default';
$this->headLink()->appendStylesheet($basePath . '/vendor/libra/twitter-bootstrap-assets/css/bootstrap.css')
                 ->appendStylesheet($basePath . '/vendor/libra/twitter-bootstrap-assets/css/bootstrap-responsive.css')
                 //->appendStylesheet($basePath . '/vendor/jquery-ui/css/smoothness/jquery-ui.custom.css')
                 ->appendStylesheet($basePath . '/vendor/libra/fancybox-assets/source/jquery.fancybox.css')
                 ->appendStylesheet($layoutPath . '/css/screen.css')
                 ->appendStylesheet($modulePath . '/css/form-actions-screen.css')
        ;

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $modulePath . '/images/favicon.ico',
        ));

$this->headScript()
    // HTML5 shim, for IE6-8 support of HTML elements
    //->appendFile($basePath . $modulePath . '/js/html5.js', null, array('conditional' => 'lt IE 9',))
    ->appendFile('http://html5shim.googlecode.com/svn/trunk/html5.js', null, array('conditional' => 'lt IE 9',))
    //->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js')
    //->appendFile('/vendor/jquery-ui/js/jquery-1.7.1.min.js')
    ->prependFile($basePath. '/vendor/libra/jquery-assets/js/jquery.min.js')
    ->appendFile($basePath. '/vendor/libra/jquery-assets/js/jquery-migrate.min.js')
    //->appendFile('/vendor/jquery-ui/js/jquery-ui.custom.min.js')
    ->appendFile($basePath . '/vendor/libra/twitter-bootstrap-assets/js/bootstrap.js')
    ->appendFile($basePath . '/vendor/libra/fancybox-assets/source/jquery.fancybox.js')
    ->appendFile($modulePath . '/js/form-actions.js')
    ;

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php $this->headTitle('Administration') ?>
    <?php echo $this->headTitle('Libra CMS') ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>

    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="http://libra-cms.ejoom.com"><span>♎</span></a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              <a href="<?php echo $basePath ?>/" target="_blank" style="margin-right: 20px;"><?php echo $this->translate('View Site') ?></a>
              <span>Signed in as <a href="<?php echo $this->url('zfcuser') ?>"><?php echo $this->zfcUserDisplayName() ?></a></span>
            </p>
            <?php echo $this->navigation() ?>
            <?php echo $this->render('topmenu') ?>
          </div><!--/.nav-collapse -->
        </div><!--/.fluid-container-->
      </div>
    </div>

    <header style="min-height: 20px;">
      <div class="container-fluid">
        <div class="row-fluid">
          <?php echo $this->header ?>
        </div>
      </div>
    </header>

    <div class="container-fluid">

      <?php echo $this->content ?>

      <hr>

      <footer>
        <p>&copy; 2008 - <?php echo date('Y') ?> by Ejoom Software Inc. All rights reserved.</p>
      </footer>

    </div><!--/.fluid-container-->
    <?php echo $this->inlineScript() ?>
  </body>

</html>
