<?php
$this->headTitle()->setSeparator(' - ')->setAutoEscape(false);

$basePath = $this->basePath();
$modulePath = $basePath . '/vendor/libra/libra-app';
$layoutPath = $basePath . '/vendor/libra/libra-app/layout/admin-default';
$this->headLink()
    ->appendStylesheet($basePath . '/vendor/libra/twitter-bootstrap-assets/css/bootstrap.css')
    ->appendStylesheet($basePath . '/vendor/libra/twitter-bootstrap-assets/css/bootstrap-responsive.css')
    //->appendStylesheet($basePath . '/vendor/jquery-ui/css/smoothness/jquery-ui.custom.css')
    ->appendStylesheet($basePath . '/vendor/libra/fancybox-assets/source/jquery.fancybox.css')
    ->appendStylesheet($modulePath . '/css/form-actions-screen.css')
    //->appendStylesheet($basePath . '/vendor/libra/datatables-assets/css/jquery.dataTables.css')
    ->appendStylesheet($layoutPath . '/css/screen.css')
;

$this->headLink(array(
    'rel'  => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $modulePath . '/images/favicon.ico',
));

$this->headScript()
    //->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js')
    //->appendFile('/vendor/jquery-ui/js/jquery-1.7.1.min.js')
    ->prependFile($basePath. '/vendor/libra/jquery-assets/js/jquery.min.js')
    ->prependFile(
        $modulePath . '/js/respond.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9',)
    )
    // HTML5 shim, for IE6-8 support of HTML elements
    //->appendFile($modulePath . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->appendFile(
        'http://html5shim.googlecode.com/svn/trunk/html5.js',
        'text/javascript',
        array('conditional' => 'lt IE 9',)
    )
    ->appendFile($basePath. '/vendor/libra/jquery-assets/js/jquery-migrate.min.js')
    //->appendFile('/vendor/jquery-ui/js/jquery-ui.custom.min.js')
    ->appendFile($basePath . '/vendor/libra/twitter-bootstrap-assets/js/bootstrap.js')
    ->appendFile($basePath . '/vendor/libra/fancybox-assets/source/jquery.fancybox.js')
    ->appendFile($modulePath . '/js/form-actions.js')
    ->appendFile($layoutPath . '/js/main.js')
    ->appendFile($basePath . '/vendor/libra/datatables-assets/js/jquery.dataTables.min.js')
    ;

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php $this->headTitle('Administration') ?>
    <?php echo $this->headTitle('Libra CMS') ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>

    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://www.ejoom.com/libra-cms/" target="_blank"><span>♎</span></a>
        </div>
        <div class="collapse navbar-collapse">
          <p class="navbar-text pull-right">
            <a href="<?php echo $basePath ?>/" target="_blank" style="margin-right: 20px;"><?php echo $this->translate('View Site') ?></a>
            <span>Signed in as <a href="<?php echo $this->url('zfcuser') ?>"><?php echo $this->zfcUserDisplayName() ?></a></span>
          </p>
          <?php // echo $this->navigation() ?>
          <?php //echo $this->ztbNavigation('AdminNavigation')
            $options = array(
                'ulClass' => 'nav navbar-nav',
            );
            echo $this->navigation()->findHelper('menu')->renderMenu(null, $options);
            echo $this->render('topmenu')
          ?>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <header style="min-height: 20px;">
      <div class="container-fluid">
        <div class="row">
          <?php echo $this->header ?>
        </div>
      </div>
    </header>

    <div class="container-fluid">

      <?php echo $this->content ?>

      <hr>

      <footer>
        <p>&copy; 2008 - <?php echo date('Y') ?> by <a href="http://www.ejoom.com" target="_blank">eJoom Software</a>. All rights reserved.</p>
      </footer>

      <?php
        $scriptRunDuration = ceil((microtime(true) - @$_SERVER['REQUEST_TIME_FLOAT']) * 1000);
      ?>
      <p class="text-muted"><small><?php echo $this->translate(sprintf("Generated in <b>%s</b> ms", $scriptRunDuration)) ?></small></p>

    </div><!--/.fluid-container-->
    <?php echo $this->inlineScript() ?>
  </body>

</html>
