<ul class="nav navbar-nav">
  <li class="divider-vertical"></li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      Configuration
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li>
        <a href="<?php echo $this->url('admin/libra-app/config/general', array('action' => 'edit')) ?>" 
           onclick="$('generalModal').modal()">
          <i class="icon-cog"></i> General
        </a>
       </li>
      <li>
        <a href="<?php echo $this->url('admin/default', array('controller' => 'translation', 'action' => 'index')) ?>">
          <i class="icon-retweet"></i> Translation
        </a>
       </li>
    </ul>
  </li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <i class="glyphicon glyphicon-question-sign icon-white" title="Help"></i>
    </a>
    <ul class="dropdown-menu">
      <li>
        <a href="<?php echo $this->url('admin/libra-app/index', array('action' => 'help')) ?>">
          About Libra CMS
        </a>
      </li>
    </ul>
  </li>
</ul>
