<ul class="nav">
  <li class="divider-vertical"></li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      Configuration
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li>
        <a href="<?php echo $this->url('admin/libra-app/config/general', array('action' => 'edit')) ?>" 
           onclick="$('generalModal').modal()">
          <i class="icon-cog"></i> General
        </a>
       </li>
      <li>
        <a href="<?php echo $this->url('default', array('controller' => 'translation', 'action' => 'index')) ?>">
          <i class="icon-retweet"></i> Translation
        </a>
       </li>
    </ul>
    <li>
      <a href="<?php echo $this->url('default', array('controller' => 'libra-app', 'action' => 'help')) ?>">
        <i class="icon-question-sign icon-white" title="Help"></i>
      </a>
    </li>
  </li>
</ul>