<h1>Home</h1>
<h2>Desctiption</h2>
<p>
	<strong>Libra CMS</strong> -&nbsp; is simple Content Management System (CMS) written at <strong>Zend Framework 2</strong> and existing modules from <a href="http://modules.zendframework.com/">http://modules.zendframework.com/</a> .</p>
<p>
	Base concepts:</p>
<p>
	It show functionality of new ZF2 framework and I hope It will be a good guid for novices to utilize feateures of ZF 2.</p>
<p>
	Features:</p>
<ul>
	<li>
		It has SEO freindly URL and meta kewrods/description fields.</li>
	<li>
		It has <a href="http://demo.libra-cms.ejoom.com/admin/">administration</a> and article managment. (login admin, password: demo12 ). By stability reasons of this site It was closed. Demo accessible at <a target="_blank" href="http://demo.libra-cms.ejoom.com">demo.libra-cms.ejoom.com</a>, as well as you can view <a href="/en/images">images</a> of administration.</li>
	<li>
		It created with supporting multilanguage. Now site done for 2 languages Russian and Eanglish.</li>
	<li>
		It has login and registraion of new users system by ZfcUsers module and custom redirect page after sign in.</li>
	<li>
		It has user managment.</li>
	<li>
		It has autogenerating menu.</li>
	<li>
		It has simple article editing by FCKEditor,</li>
	<li>
		It has simple Acl and temporary added access by IP. I just not removed it</li>
	<li>
		It use twitter bootstrap for form and design. So you can serfe site at mobile.</li>
	<li>
		It will be based at jQuery.</li>
</ul>
<p>
	You can download code <a href="/en/index/download">this</a>&nbsp;&nbsp;&nbsp; (for administration: password: 111111, user: admin).</p>
<p>
	&nbsp;</p>
<p>
	With any questions, suggestions or&nbsp; comments write me at <a href="mailto:duke@ejoom.com">duke@ejoom.com</a></p>
<p>
	I'm also available via&nbsp; <a href="irc://irc.freenode.net/zftalk">#zftalk on Freenode</a>. Use free to ask.</p>

<p>This is default page for Libra-CMS if you didn't install libra-article module</p>